# fly.toml app configuration file generated for chat-demo-z3h9ea on 2025-03-02T16:31:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chat-demo-z3h9ea'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
