// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/mgjules/chat-demo/chat"
	"github.com/mgjules/chat-demo/user"
)

func Page(user *user.User, room *chat.Room, cErr *chat.Error) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><meta charset=\"utf-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><title>Chat Demo</title><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><style>\n\t\t\t\t[un-cloak] {\n\t\t\t\t\tdisplay: none\n\t\t\t\t}\n\t\t\t</style><script type=\"module\">\n\t\t\t  // UnoCSS\n\t\t\t\timport { presetWind, presetIcons } from 'https://cdn.jsdelivr.net/npm/unocss@0.55.7/+esm'\n\t\t\t\timport initUnocssRuntime from 'https://cdn.jsdelivr.net/npm/@unocss/runtime@0.55.7/+esm'\n\t\t\t\timport reset from 'https://cdn.jsdelivr.net/npm/@unocss/reset@0.55.7/tailwind-compat.css' with { type: 'css' };\n\n\t\t\t\tdocument.adoptedStyleSheets = [reset];\n\n\t\t\t\t// UnoCSS default configuration.\n\t\t\t\tinitUnocssRuntime({\n\t\t\t\t\tdefaults: {\n\t\t\t\t\t\tpresets: [\n\t\t\t\t\t\t\tpresetWind(),\n\t\t\t\t\t\t\tpresetIcons({\n\t\t\t\t\t\t\t\tcdn: 'https://esm.sh/'\n\t\t\t\t\t\t\t})\n\t\t\t\t\t\t],\n\t\t\t\t\t\trules: [\n\t\t\t\t\t\t\t['overflow-anchor-none', { \"overflow-anchor\": 'none' }],\n\t\t\t\t\t\t\t['overflow-anchor-auto', { \"overflow-anchor\": 'auto' }],\n\t\t\t\t\t\t],\n\t\t\t\t\t}\n\t\t\t\t})\n\t\t\t</script></head><body un-cloak class=\"bg-coolgray-800 text-coolgray-200 scroll-smooth\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Chat(user, room, cErr).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
